/* Done Right: generate the catalog migration (service groups, services, licences, licence rules, areas)
 * from the app's own data files, so the database enforces exactly what the app shows.
 * Regenerate (macOS): osascript -l JavaScript tools/gen_catalog_sql.js > supabase/migrations/20260922000200_catalog.sql
 * Elsewhere: open tools/catalog-sql.html and download the file. The test suite fails if the committed file drifts.
 * After the first deploy, ship catalog changes as a NEW timestamped migration (the output is idempotent). */
(function (DR) {
  'use strict';
  const q = (v) => (v == null ? 'null' : typeof v === 'number' || typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
  // Idempotent: re-running (or shipping a regenerated copy as a new migration) updates rows in place.
  const rows = (table, cols, list, key) => (list.length
    ? `insert into public.${table} (${cols.join(', ')}) values\n${list.map((r) => `  (${r.map(q).join(', ')})`).join(',\n')}\n`
      + `on conflict (${key.join(', ')}) do ${cols.length > key.length ? `update set ${cols.filter((c) => !key.includes(c)).map((c) => `${c} = excluded.${c}`).join(', ')}` : 'nothing'};\n`
    : '');

  DR.catalogSQL = function catalogSQL() {
    const groups = DR.GROUPS.map((g) => [g.id, g.name, !!g.bg]);
    const services = DR.ALL_SUBS.map((s) => [s.id, s.groupId, s.name, s.unit, s.duration, s.price, DR.lic.bgRequired(s.id)]);
    const licences = Object.entries(DR.LICENCES).map(([id, l]) => [id, l.cc, l.name, l.issuer, l.register || null]);
    const rules = [];
    Object.keys(DR.LICENSING).sort().forEach((sid) => {
      if (!DR.SUB[sid]) return;
      ['SG', 'MY'].forEach((cc) => DR.lic.rules(sid, cc).forEach((options, gi) => options.forEach((lid) => rules.push([sid, cc, gi + 1, lid]))));
    });
    const areas = ['SG', 'MY'].flatMap((cc) => DR.AREAS[cc].map((a) => [cc, a.n, a.r, a.lat, a.lng]));
    return [
      '-- Done Right: catalog data. GENERATED by tools/catalog-sql.js from js/data/*.js; do not edit by hand.',
      `-- ${groups.length} groups, ${services.length} services, ${licences.length} licence types, ${rules.length} licence rules, ${areas.length} areas.`,
      '',
      rows('service_groups', ['id', 'name', 'background_check'], groups, ['id']),
      rows('service_types', ['id', 'group_id', 'name', 'unit', 'duration_min', 'base_price_sgd', 'background_check'], services, ['id']),
      rows('licence_types', ['id', 'country', 'name', 'issuer', 'register'], licences, ['id']),
      '-- licence rules are replaced as a whole so removed requirements disappear too',
      'delete from public.licence_rules;',
      rows('licence_rules', ['service_id', 'country', 'req_group', 'licence_id'], rules, ['service_id', 'country', 'req_group', 'licence_id']),
      rows('areas', ['country', 'name', 'region', 'lat', 'lng'], areas, ['country', 'name']),
    ].join('\n');
  };
})(window.DR);
